// This file is generated by omniidl (C++ backend)- omniORB_4_0. Do not edit.
#ifndef __CorbaTypes_hh__
#define __CorbaTypes_hh__

#ifndef USE_omniORB_logStream
#define USE_omniORB_logStream
#endif

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CorbaTypes
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CorbaTypes
#endif






#ifdef USE_stub_in_nt_dll
#ifndef USE_core_stub_in_nt_dll
#define USE_core_stub_in_nt_dll
#endif
#ifndef USE_dyn_stub_in_nt_dll
#define USE_dyn_stub_in_nt_dll
#endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE Base_Bus

_CORBA_MODULE_BEG

  _CORBA_MODULE CorbaTypes

  _CORBA_MODULE_BEG

    enum EDatapointAlarm { NoAlarm, OverScaleHighAlarm, OverScaleLowAlarm, VeryHighAlarm, HighAlarm, LowAlarm, VeryLowAlarm, TrueAlarm, FalseAlarm, GeneralAlarm /*, __max_EDatapointAlarm=0xffffffff */ };
    typedef EDatapointAlarm& EDatapointAlarm_out;

    _CORBA_MODULE_VAR _dyn_attr const CORBA::TypeCode_ptr _tc_EDatapointAlarm;

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_Base_Bus
_CORBA_MODULE_BEG

  _CORBA_MODULE CorbaTypes
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(Base_Bus::CorbaTypes::EDatapointAlarm _e, cdrStream& s) {
  ::operator>>=((CORBA::ULong)_e, s);
}

inline void operator <<= (Base_Bus::CorbaTypes::EDatapointAlarm& _e, cdrStream& s) {
  CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  switch (_0RL_e) {
    case Base_Bus::CorbaTypes::NoAlarm:

    case Base_Bus::CorbaTypes::OverScaleHighAlarm:

    case Base_Bus::CorbaTypes::OverScaleLowAlarm:

    case Base_Bus::CorbaTypes::VeryHighAlarm:

    case Base_Bus::CorbaTypes::HighAlarm:

    case Base_Bus::CorbaTypes::LowAlarm:

    case Base_Bus::CorbaTypes::VeryLowAlarm:

    case Base_Bus::CorbaTypes::TrueAlarm:

    case Base_Bus::CorbaTypes::FalseAlarm:

    case Base_Bus::CorbaTypes::GeneralAlarm:


    _e = (Base_Bus::CorbaTypes::EDatapointAlarm) _0RL_e;
    break;
  default:
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (CORBA::CompletionStatus)s.completion());
  }
}

void operator<<=(CORBA::Any& _a, Base_Bus::CorbaTypes::EDatapointAlarm _s);
CORBA::Boolean operator>>=(const CORBA::Any& _a, Base_Bus::CorbaTypes::EDatapointAlarm& _s);





#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CorbaTypes
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CorbaTypes
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CorbaTypes
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CorbaTypes
#endif

#endif  // __CorbaTypes_hh__

